#!/bin/bash

root=$PWD
resized='romart';
boxart="Named_Boxarts"
width=128
rmdir $resized
systems=($(ls -F | grep /))
mkdir $resized
bar="⣿"

echo "--------------------------------------------------------------------------"
echo -e "root -> ${root}"
echo "--------------------------------------------------------------------------"
for system in "${systems[@]}"
do
  system="${system%?}";
  cd $system/$boxart;
  total=($(ls -l | grep -v ^l | wc -l))
  echo "$system - has $total files";

  TMP="${root}/${resized}/${system}"
  mkdir $TMP

  complete=0
  percent=0
  calc=0
  find . -type f -name "*.png" -print0 | while IFS= read -r -d '' file;
  do
    bars=""
    complete=$((complete+1))
    calc=$(( (100 * complete / total + (1000 * complete / total % 10 >= 5 ? 1 : 0)) / 2 ))

    if [ "$calc" -gt "$percent" ];then
      clear
      percent=$calc
      for (( i=0; i<$percent; ++i)); do
        bars="${bars}${bar}"
      done
      echo "Converting ${system} files:"
      echo "$((percent * 2 ))% ${bars}"
    fi

    convert "${file}" -resize ${width} "${TMP}/${file}"
  done


  cd $root
done
echo "--------------------------------------------------------------------------"
